rm -rf ./coil_core/__pycache__
rm -rf ./coil_core/*.pyc
rm -rf ./configs/__pycache__
rm -rf ./configs/*.pyc
rm -rf ./drive/__pycache__
rm -rf ./drive/*.pyc
rm -rf ./input/__pycache__
rm -rf ./input/*.pyc
rm -rf ./logger/__pycache__
rm -rf ./logger/*.pyc
rm -rf ./network/__pycache__
rm -rf ./network/*.pyc
rm -rf ./network/models/__pycache__
rm -rf ./network/models/*.pyc
rm -rf ./utils/__pycache__
rm -rf ./utils/*.pyc
rm -rf ./visualization/__pycache__
rm -rf ./visualization/*.pyc
