
#### General Configuration Parameters ####
SAVE_SCHEDULE: range(0, 10000000, 2000)

NUMBER_OF_LOADING_WORKERS: 12   # Number of threads used in the data loader

#### Input related parameters ####
SENSORS:
  rgb: (3, 88, 200)
MEASUREMENTS:
  targets: (31)

#task yaml
BATCH_SIZE: 30
NUMBER_ITERATIONS: 20000000
NUMBER_FRAMES_FUSION: 1
STEERING_DIVISION: [0.05, 0.05, 0.1, 0.3, 0.3, 0.1, 0.05, 0.05]
LABELS_DIVISION: [[2]]
TARGETS: ['steer', 'throttle', 'brake']
INPUTS: ['speed_module']
NUMBER_FRAMES_FUSION: 1
NUMBER_IMAGES_SEQUENCE: 1
SEQUENCE_STRIDE: 1
AUGMENT_LATERAL_STEERINGS: 6  # Depending on this value there is a constant multiplying lateral steers
SPEED_FACTOR: 40.0
TRAIN_DATASET_NAME: 'SeqTrain'

#GAN RELATED PARAMETERS
GANMODEL_NAME: 'LSDcontrol_task_2d'
LOSS_FUNCTION: 'WGANmix'
LR_D: 0.0002
LR_G: 0.0002
LEARNING_RATE: 0.0002
SKIP: 0
TYPE: "task"
L1_WEIGHT: 100.0
LABSMOOTH: 1
PRETRAINED: "IL"
TRAIN_TYPE: 'WGAN'
SEED: 1234
CLAMP: 0.01
N_CRITIC: 5
TASK_ADV_WEIGHT: 0.1
IF_AUG : True
IF_POOL : True
IL_AGENT_PATH : 'Encoder_IL.pth'
DECODER_RECON_PATH : 'Decoder_Recon.pth'
TARGET_DOMAIN_PATH : '/datatmp/Datasets/UNIT_LW1toEW12/trainB'
IF_AUG_SRC : False
IF_AUG_TGT : False


#### Testing Related Parameters ####
TEST_SCHEDULE: range(0, 10000000, 2000)  # The frequency the model is actually tested.


#### Network Related Parameters ####


MODEL_NAME: 'coil_icra'
TRAINING_SCHEDEULE: [[50000, 0.5], [100000, 0.5 * 0.5], [150000, 0.5 * 0.5 * 0.5], [200000, 0.5 * 0.5 * 0.5 * 0.5],[250000, 0.5 * 0.5 * 0.5 * 0.5 * 0.5]]  # Number of iterations, multiplying factor

#TODO check how to use this part
BRANCH_LOSS_WEIGHT: [0.95, 0.95, 0.95, 0.95, 0.05]

VARIABLE_WEIGHT:
  Steer: 0.5
  Gas: 0.45
  Brake: 0.05
  Speed: 1.0



#### Simulation Related Parameters ####
CITY_NAME: 'Town01'
IMAGE_CUT: [115, 510]  # How you should cut the input image that is received from the server
USE_ORACLE: False
